'use client';
import { FormEvent, useEffect, useState } from 'react';

type Result = { id: string; status: string; score?: number | null; reportUrl?: string | null; error?: string | null };

export default function Home() {
  const [token,setToken]=useState(''); const [email,setEmail]=useState(''); const [url,setUrl]=useState(''); const [tier,setTier]=useState('quick_win'); const [competitors,setCompetitors]=useState(''); const [result,setResult]=useState<Result|null>(null); const [busy,setBusy]=useState(false);
  async function submit(e: FormEvent){ e.preventDefault(); setBusy(true); setResult(null); const r=await fetch('/api/audits',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${token}`},body:JSON.stringify({email,url,tier,competitorUrls:competitors.split('\n').map(x=>x.trim()).filter(Boolean)})}); const j=await r.json(); setBusy(false); if(!r.ok){setResult({id:'',status:'error',error:j.error});return;} setResult(j); }
  useEffect(()=>{ if(!result?.id || ['completed','failed'].includes(result.status)) return; const t=setInterval(async()=>{const r=await fetch(`/api/audits/${result.id}`,{headers:{authorization:`Bearer ${token}`}}); if(r.ok)setResult(await r.json());},3000); return()=>clearInterval(t); },[result?.id,result?.status,token]);
  return <main><section className="hero"><span className="eyebrow">Automated fulfillment MVP</span><h1>Website SEO & UX Audit Engine</h1><p>Run the same pipeline your Etsy orders use: safe crawl → PageSpeed → structured AI analysis → branded PDF → email.</p></section><section className="card"><form onSubmit={submit}><label>Admin token<input type="password" value={token} onChange={e=>setToken(e.target.value)} required/></label><div className="grid"><label>Customer email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Website URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com" required/></label></div><label>Audit tier<select value={tier} onChange={e=>setTier(e.target.value)}><option value="quick_win">Quick Win</option><option value="full_site">Full Site & UX Breakdown</option><option value="competitor_conquest">Competitor Conquest</option></select></label>{tier==='competitor_conquest'&&<label>Competitor URLs, one per line<textarea value={competitors} onChange={e=>setCompetitors(e.target.value)} rows={4}/></label>}<button disabled={busy}>{busy?'Starting…':'Run audit'}</button></form>{result&&<div className={`status ${result.status}`}><strong>{result.status.replaceAll('_',' ')}</strong>{result.score!=null&&<span>Score: {result.score}/100</span>}{result.error&&<span>{result.error}</span>}{result.reportUrl&&<a href={result.reportUrl} target="_blank">Open PDF report</a>}</div>}</section><footer>The term 'Etsy' is a trademark of Etsy, Inc. This Application uses Etsy's API, but is not endorsed or certified by Etsy.</footer></main>;
}
