import type { AuditAnalysis, AuditTier, PageSpeedSummary, SiteScrape } from './types';
import { env } from './env';
import { productForTier } from './products';

const e = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[c]!));
const severityLabel = (s: string) => s === 'critical' ? 'Critical' : s === 'warning' ? 'Improve' : 'Working well';

export function renderReportHtml(input: { analysis: AuditAnalysis; site: SiteScrape; pageSpeed: PageSpeedSummary[]; tier: AuditTier; createdAt: string }) {
  const { analysis, site, pageSpeed, tier } = input;
  const product = productForTier(tier);
  const scoreCards = Object.entries(analysis.scores).map(([k,v]) => `<div class="score"><strong>${v}</strong><span>${e(k.toUpperCase())}</span></div>`).join('');
  const actions = analysis.actionItems.map((a, i) => `<article class="action ${e(a.severity)}"><div class="action-head"><span class="badge">${severityLabel(a.severity)}</span><span>${e(a.category)} · ${e(a.impact)} impact · ${e(a.effort)} effort</span></div><h3>${i+1}. ${e(a.title)}</h3><p><b>Why it matters:</b> ${e(a.why)}</p><p><b>What to do:</b> ${e(a.how)}</p>${a.pageUrl ? `<p class="url">${e(a.pageUrl)}</p>`:''}</article>`).join('');
  const rewrites = analysis.rewrites.map(r => `<article class="rewrite"><p class="url">${e(r.pageUrl)}</p><p><b>SEO title</b><br>${e(r.title)}</p><p><b>Meta description</b><br>${e(r.metaDescription)}</p><p><b>Primary H1</b><br>${e(r.primaryH1)}</p><p><b>CTA</b><br>${e(r.cta)}</p></article>`).join('');
  const ps = pageSpeed.map(p => `<tr><td>${e(p.strategy)}</td><td>${e(new URL(p.url).pathname || '/')}</td><td>${p.scores.performance ?? '—'}</td><td>${p.scores.accessibility ?? '—'}</td><td>${p.scores.seo ?? '—'}</td></tr>`).join('');
  const comp = tier === 'competitor_conquest' && analysis.competitorGap ? `<section><h2>Competitor gap analysis</h2><p>${e(analysis.competitorGap.summary)}</p><div class="cols"><div><h3>Your wins</h3><ul>${analysis.competitorGap.wins.map(x=>`<li>${e(x)}</li>`).join('')}</ul></div><div><h3>Gaps</h3><ul>${analysis.competitorGap.gaps.map(x=>`<li>${e(x)}</li>`).join('')}</ul></div><div><h3>Opportunities</h3><ul>${analysis.competitorGap.opportunities.map(x=>`<li>${e(x)}</li>`).join('')}</ul></div></div></section>` : '';
  return `<!doctype html><html><head><meta charset="utf-8"><style>
@page{size:A4;margin:16mm 14mm 18mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#17202a;font-size:11px;line-height:1.45;margin:0}h1{font-size:30px;line-height:1.05;margin:8px 0 10px}h2{font-size:20px;margin:24px 0 10px;border-bottom:1px solid #dde3ea;padding-bottom:6px}h3{font-size:14px;margin:7px 0}.muted,.url{color:#64748b}.cover{min-height:240mm;display:flex;flex-direction:column;justify-content:center}.brand{font-weight:800;letter-spacing:.12em;text-transform:uppercase}.hero-score{font-size:74px;font-weight:800;line-height:1}.hero-score small{font-size:18px;color:#64748b}.summary{font-size:16px;max-width:145mm}.scores{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:14px 0}.score{border:1px solid #dce3ea;border-radius:12px;padding:12px;text-align:center}.score strong{display:block;font-size:24px}.score span{font-size:9px;color:#64748b}.quick{background:#f6f8fb;border-radius:14px;padding:12px 18px}.action,.rewrite{border:1px solid #dce3ea;border-radius:12px;padding:12px;margin:9px 0;break-inside:avoid}.action.critical{border-left:5px solid #b91c1c}.action.warning{border-left:5px solid #b45309}.action.good{border-left:5px solid #15803d}.action-head{display:flex;justify-content:space-between;color:#64748b;font-size:9px;text-transform:uppercase;letter-spacing:.04em}.badge{font-weight:700}.rewrite{background:#fafafa}table{width:100%;border-collapse:collapse}th,td{padding:7px;border-bottom:1px solid #e5e7eb;text-align:left}.cols{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.cols>div{border:1px solid #e5e7eb;border-radius:10px;padding:8px}.footer-note{margin-top:25px;color:#64748b;font-size:9px}.page-break{break-before:page}
</style></head><body>
<section class="cover"><div class="brand">${e(env.REPORT_BRAND_NAME)}</div><p class="muted">${e(product.name)}</p><h1>${e(analysis.reportTitle)}</h1><p class="url">${e(site.startUrl)}</p><div class="hero-score">${analysis.overallScore}<small>/100</small></div><p class="summary">${e(analysis.executiveSummary)}</p><div class="scores">${scoreCards}</div><p class="muted">Prepared ${e(new Date(input.createdAt).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'}))} · ${e(product.shortName)}</p></section>
<section class="page-break"><h2>Priority quick wins</h2><ol class="quick">${analysis.quickWins.map(x=>`<li>${e(x)}</li>`).join('')}</ol><h2>Performance snapshot</h2><table><thead><tr><th>Device</th><th>Page</th><th>Performance</th><th>Accessibility</th><th>SEO</th></tr></thead><tbody>${ps}</tbody></table><h2>Site coverage</h2><p>${site.pages.length} page(s) reviewed. robots.txt: ${site.robotsTxt ? 'found' : 'not found'} · sitemap directive: ${site.hasSitemap ? 'found' : 'not found'} · llms.txt: ${site.llmsTxt ? 'found' : 'not found'}.</p></section>
<section class="page-break"><h2>Action plan</h2>${actions}</section>
${rewrites ? `<section class="page-break"><h2>Copy & metadata rewrites</h2>${rewrites}</section>`:''}
${comp ? `<section class="page-break">${comp}</section>`:''}
<p class="footer-note">Automated audit findings are decision support, not a guarantee of search rankings, revenue, accessibility compliance, or platform eligibility.</p>
</body></html>`;
}
