'use client';
import { useEffect, useState } from 'react';
import { AdminShell } from '@/components/AdminShell';
import { Frame, Sparkle } from '@/components/Frame';
import { SectionTitle } from '@/components/SectionTitle';
import { useAdminToken } from '@/components/useAdminToken';
import { withBasePath } from '@/lib/app-paths';
import type { AuditSummary } from '@/components/types';
function domain(url:string){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url}}
export default function Queue(){const {token}=useAdminToken();const [queue,setQueue]=useState<AuditSummary[]>([]);const [busy,setBusy]=useState(false);async function load(){if(!token)return;setBusy(true);const r=await fetch(withBasePath('/api/audits?status=awaiting_etsy_upload'),{headers:{authorization:`Bearer ${token}`}});const j=await r.json();if(r.ok)setQueue(j.audits??[]);setBusy(false)}useEffect(()=>{load()},[token]);
 async function download(a:AuditSummary){const r=await fetch(withBasePath(`/api/audits/${a.id}/report`),{headers:{authorization:`Bearer ${token}`}});if(!r.ok)return;const blob=await r.blob();const href=URL.createObjectURL(blob);const el=document.createElement('a');el.href=href;el.download=`MsSaraJo-${a.etsyReceiptId??a.id}.pdf`;el.click();URL.revokeObjectURL(href)}async function complete(a:AuditSummary){const r=await fetch(withBasePath(`/api/audits/${a.id}/etsy-complete`),{method:'POST',headers:{authorization:`Bearer ${token}`}});if(r.ok)load()}
 return <AdminShell><SectionTitle eyebrow="DELIVERY WORKFLOW" title="Etsy Report Queue" script="Finished work, ready to send." body="Download each completed PDF, attach it to the matching made-to-order Etsy order, then confirm delivery here."/><div className="queue-toolbar"><button className="secondary-btn" onClick={load} disabled={busy}>{busy?'Refreshing…':'Refresh queue ↻'}</button></div>{!queue.length?<Frame tone="green" className="empty-state"><Sparkle/><h2>Queue is clear</h2><p>No reports are currently waiting for Etsy upload confirmation.</p></Frame>:<div className="branded-queue">{queue.map(a=><Frame tone="coral" key={a.id} className="queue-row"><span className="report-gem quick_win">✦</span><div><span className="mini-label">{a.product}</span><h2>{domain(a.targetUrl)}</h2><p>Receipt {a.etsyReceiptId??'—'} · {a.score!=null?`Score ${a.score}/100 · `:''}{new Date(a.createdAt).toLocaleDateString()}</p></div><div className="queue-row-actions"><button onClick={()=>download(a)}>Download PDF</button><button className="secondary-btn" onClick={()=>complete(a)}>Mark uploaded</button></div></Frame>)}</div>}</AdminShell>}
